
import React from 'react';
import { Button } from '@/components/ui/button';
import { LogOut, Users, Bell, Download } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { useRealtime } from '@/contexts/RealtimeContext';
import { useNotificationHandler } from './NotificationHandler';
import NotificationPanel from './NotificationPanel';
import jsPDF from 'jspdf';

interface HeaderProps {
  userRole: 'admin' | 'member';
  userName: string;
  onLogout: () => void;
  onRoleSwitch?: () => void;
  notifications?: number;
  onNotificationClick?: () => void;
}

const Header = ({
  userRole,
  userName,
  onLogout,
  onRoleSwitch,
  notifications = 0,
  onNotificationClick
}: HeaderProps) => {
  const { notifications: realtimeNotifications, tasks, deleteNotification, clearAllNotifications } = useRealtime();
  
  const {
    isNotificationPanelOpen,
    setIsNotificationPanelOpen,
    handleMarkAsRead,
    handleMarkAllAsRead,
    unreadNotifications
  } = useNotificationHandler({
    notifications: realtimeNotifications
  });

  // Helper function to convert Urdu text to readable English format
  const convertUrduToReadable = (urduText: string): string => {
    const urduToEngMap: { [key: string]: string } = {
      'نیا ٹاسک': 'New Task',
      'ٹاسک اپڈیٹ': 'Task Update', 
      'ٹاسک مکمل': 'Task Complete',
      'ٹاسک حذف': 'Task Deleted',
      'اعلیٰ': 'High Priority',
      'درمیانہ': 'Medium Priority',
      'کم': 'Low Priority',
      'نیا': 'New',
      'جاری': 'In Progress',
      'جائزہ': 'Under Review',
      'مکمل': 'Complete',
      'ٹو ڈو': 'To Do',
      'انتظار': 'Pending',
      'ختم': 'Done'
    };
    
    let convertedText = urduText;
    Object.keys(urduToEngMap).forEach(urdu => {
      convertedText = convertedText.replace(new RegExp(urdu, 'g'), urduToEngMap[urdu]);
    });
    
    return convertedText || urduText;
  };

  const generatePDFReport = async () => {
    try {
      console.log('Generating readable PDF report...');
      
      if (tasks.length === 0) {
        alert('No tasks available to generate report');
        return;
      }

      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      
      // Add header image
      try {
        const img = new Image();
        img.crossOrigin = 'anonymous';
        img.src = '/lovable-uploads/2dbef948-c996-4222-9241-afa8cbb093b0.png';
        await new Promise((resolve, reject) => {
          img.onload = resolve;
          img.onerror = reject;
          setTimeout(reject, 5000);
        });
        
        const imgWidth = 160;
        const imgHeight = 35;
        const x = (pageWidth - imgWidth) / 2;
        pdf.addImage(img, 'PNG', x, 10, imgWidth, imgHeight);
      } catch (error) {
        console.log('Could not load header image, continuing without it');
      }

      let yPosition = 60;
      
      // Set font to standard fonts for better compatibility
      pdf.setFont('helvetica', 'normal');
      
      // Add title
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Majlis Dawatul Haq - Task Management Report', pageWidth / 2, yPosition, { align: 'center' });
      yPosition += 15;
      
      // Add date
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'normal');
      const currentDate = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      });
      pdf.text(`Generated Date: ${currentDate}`, pageWidth / 2, yPosition, { align: 'center' });
      yPosition += 8;
      pdf.text(`Report Generated By: ${userName}`, pageWidth / 2, yPosition, { align: 'center' });
      yPosition += 20;
      
      // Task Summary
      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Task Summary:', 20, yPosition);
      yPosition += 12;
      
      const todoTasks = tasks.filter(t => t.status === 'todo').length;
      const inProgressTasks = tasks.filter(t => t.status === 'inprogress').length;
      const reviewTasks = tasks.filter(t => t.status === 'review').length;
      const doneTasks = tasks.filter(t => t.status === 'done').length;
      
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Total Tasks: ${tasks.length}`, 25, yPosition);
      yPosition += 7;
      pdf.text(`To Do: ${todoTasks}`, 25, yPosition);
      yPosition += 7;
      pdf.text(`In Progress: ${inProgressTasks}`, 25, yPosition);
      yPosition += 7;
      pdf.text(`Under Review: ${reviewTasks}`, 25, yPosition);
      yPosition += 7;
      pdf.text(`Completed: ${doneTasks}`, 25, yPosition);
      yPosition += 15;
      
      // Task Details
      pdf.setFontSize(14);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Task Details:', 20, yPosition);
      yPosition += 12;
      
      const statusLabels = {
        todo: 'To Do',
        inprogress: 'In Progress',
        review: 'Under Review',
        done: 'Completed'
      };

      const priorityLabels = {
        high: 'High',
        medium: 'Medium',
        low: 'Low'
      };
      
      tasks.forEach((task, index) => {
        if (yPosition > pageHeight - 50) {
          pdf.addPage();
          yPosition = 20;
        }
        
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'bold');
        
        // Convert task title to readable format
        const readableTitle = convertUrduToReadable(task.title);
        pdf.text(`${index + 1}. ${readableTitle}`, 25, yPosition);
        yPosition += 7;
        
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(9);
        
        // Convert and wrap description
        if (task.description) {
          const readableDesc = convertUrduToReadable(task.description);
          const descLines = pdf.splitTextToSize(`Description: ${readableDesc}`, pageWidth - 60);
          pdf.text(descLines, 30, yPosition);
          yPosition += descLines.length * 5;
        }
        
        // Convert assignedTo name
        const readableAssignee = convertUrduToReadable(task.assignedTo);
        pdf.text(`Assigned To: ${readableAssignee}`, 30, yPosition);
        yPosition += 5;
        pdf.text(`Status: ${statusLabels[task.status]}`, 30, yPosition);
        yPosition += 5;
        pdf.text(`Priority: ${priorityLabels[task.priority]}`, 30, yPosition);
        yPosition += 5;
        pdf.text(`Progress: ${task.progress}%`, 30, yPosition);
        yPosition += 5;
        
        const dueDate = new Date(task.dueDate).toLocaleDateString('en-US');
        pdf.text(`Due Date: ${dueDate}`, 30, yPosition);
        yPosition += 5;
        
        // Convert member notes
        if (task.memberNotes) {
          const readableNotes = convertUrduToReadable(task.memberNotes);
          const notesLines = pdf.splitTextToSize(`Member Notes: ${readableNotes}`, pageWidth - 60);
          pdf.text(notesLines, 30, yPosition);
          yPosition += notesLines.length * 5;
        }
        
        yPosition += 8;
      });
      
      // Add footer with page numbers
      const totalPages = pdf.internal.pages.length - 1;
      for (let i = 1; i <= totalPages; i++) {
        pdf.setPage(i);
        pdf.setFontSize(8);
        pdf.setFont('helvetica', 'normal');
        pdf.text(`Page ${i} of ${totalPages}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
        pdf.text('Majlis Dawatul Haq Task Management System', pageWidth / 2, pageHeight - 5, { align: 'center' });
      }
      
      // Save PDF with proper filename
      const fileName = `majlis-task-report-${new Date().toISOString().split('T')[0]}.pdf`;
      pdf.save(fileName);
      
      console.log('PDF report generated successfully:', fileName);
      alert(`Report downloaded successfully! File: ${fileName} (${tasks.length} tasks included)`);
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Error generating report. Please try again.');
    }
  };

  return (
    <>
      <header className="bg-gradient-to-r from-blue-600 to-green-600 text-white shadow-lg">
        <div className="container mx-auto px-3 sm:px-4 lg:px-6 py-3 sm:py-4">
          <div className="flex flex-col sm:flex-row justify-between items-center gap-3 sm:gap-0">
            {/* Logo and Title Section */}
            <div className="flex items-center space-x-3 sm:space-x-4 order-1 sm:order-1" dir="rtl">
              <img src="/lovable-uploads/e1652408-702e-47c9-834c-bafadef748e9.png" alt="Majlis e Dawatul Haq Logo" className="h-10 w-10 sm:h-12 sm:w-12 rounded-full bg-white p-1 flex-shrink-0" />
              <div className="text-center sm:text-right">
                <h1 className="text-lg sm:text-xl lg:text-2xl font-bold leading-tight">مجلس دعوۃ الحق</h1>
                <span className="text-xs sm:text-sm opacity-90 block mt-0.5">ٹاسک  مینجمنٹ سسٹم</span>
              </div>
            </div>

            {/* User Actions Section */}
            <div className="flex items-center gap-2 sm:gap-3 lg:gap-4 order-2 sm:order-2 flex-wrap justify-center sm:justify-end">
              {/* PDF Generation Button - Only for admin */}
              {userRole === 'admin' && (
                <Button 
                  variant="ghost" 
                  size="sm" 
                  onClick={generatePDFReport}
                  className="text-white hover:bg-white/10 p-2 sm:p-2.5"
                  title="Generate PDF Report"
                >
                  <Download className="h-4 w-4 sm:h-5 sm:w-5" />
                </Button>
              )}
              
              {/* Notification Bell */}
              <div className="relative">
                <Button 
                  variant="ghost" 
                  size="sm" 
                  onClick={() => setIsNotificationPanelOpen(true)}
                  className="text-white hover:bg-white/10 relative p-2 sm:p-2.5"
                >
                  <Bell className="h-4 w-4 sm:h-5 sm:w-5" />
                  {unreadNotifications > 0 && (
                    <Badge className="absolute -top-1 -right-1 sm:-top-2 sm:-right-2 h-4 w-4 sm:h-5 sm:w-5 flex items-center justify-center p-0 bg-red-500 text-white text-xs min-w-0 rounded-full">
                      {unreadNotifications > 9 ? '9+' : unreadNotifications}
                    </Badge>
                  )}
                </Button>
              </div>
              
              {/* User Welcome Text */}
              <div className="hidden sm:flex flex-col items-end text-right" dir="rtl">
                <span className="text-sm lg:text-base font-medium">خوش آمدید، {userName}</span>
                <span className="px-2 py-0.5 bg-white/20 rounded-full text-xs opacity-90">
                  {userRole === 'admin' ? 'منتظم' : 'رکن'}
                </span>
              </div>

              {/* Mobile User Info */}
              <div className="flex sm:hidden items-center gap-2" dir="rtl">
                <span className="text-sm font-medium">{userName}</span>
                <span className="px-2 py-0.5 bg-white/20 rounded-full text-xs">
                  {userRole === 'admin' ? 'منتظم' : 'رکن'}
                </span>
              </div>
              
              {/* Role Switch Button - Only for admin */}
              {userRole === 'admin' && onRoleSwitch && (
                <Button 
                  variant="outline" 
                  size="sm" 
                  onClick={onRoleSwitch}
                  className="text-white border-white/30 hover:bg-white/10 hover:border-white/50 transition-all duration-200 text-xs sm:text-sm px-2 sm:px-3"
                >
                  <Users className="h-3 w-3 sm:h-4 sm:w-4 ml-1 sm:mr-2" />
                  <span dir="rtl" className="hidden sm:inline">رکن کی نظر</span>
                  <span dir="rtl" className="sm:hidden">رکن</span>
                </Button>
              )}
              
              {/* Logout Button */}
              <Button 
                variant="outline" 
                size="sm" 
                onClick={onLogout}
                className="text-white border-white/30 hover:bg-white/10 hover:border-white/50 transition-all duration-200 text-xs sm:text-sm px-2 sm:px-3"
              >
                <LogOut className="h-3 w-3 sm:h-4 sm:w-4 ml-1 sm:mr-2" />
                <span dir="rtl" className="hidden sm:inline">لاگ آؤٹ</span>
                <span dir="rtl" className="sm:hidden">خروج</span>
              </Button>
            </div>
          </div>
        </div>
      </header>

      {/* Notification Panel */}
      <NotificationPanel
        notifications={realtimeNotifications}
        isOpen={isNotificationPanelOpen}
        onClose={() => setIsNotificationPanelOpen(false)}
        onMarkAsRead={handleMarkAsRead}
        onMarkAllAsRead={handleMarkAllAsRead}
        onDeleteNotification={deleteNotification}
        onClearAll={clearAllNotifications}
      />
    </>
  );
};

export default Header;
