// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
<<<<<<< HEAD
=======
import type { Database } from './types';
>>>>>>> 8d2399815ffd473f0360df2516ab0f7fc292f5d3

const SUPABASE_URL = "https://vvzrfdtrtjbyxtwkdzsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2enJmZHRydGpieXh0d2tkenNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNzc2MDksImV4cCI6MjA2NjY1MzYwOX0.4i8xB2Pn-_mKsr0TWr4FBX5os9fypWsmuJSxk7PWnuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

<<<<<<< HEAD
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
=======
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
>>>>>>> 8d2399815ffd473f0360df2516ab0f7fc292f5d3
